# Generated by Django 4.2.14 on 2024-07-12 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Кличка')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('breed', models.CharField(max_length=255, verbose_name='Порода')),
                ('color', models.CharField(max_length=255, verbose_name='Окрас')),
                ('treatment_method', models.CharField(max_length=255, verbose_name='Название и тип обработки')),
                ('start_treatment_method', models.DateField(verbose_name='Дата обработки')),
                ('end_treatment_method', models.DateField(verbose_name='Дата когда заканчивается обработка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
