# Generated by Django 4.2.14 on 2024-07-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buddy_app', '0004_rename_name_pet_pets_name_remove_pet_start_vaccine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineRabies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacсine_name', models.CharField(max_length=255, verbose_name='Название вакцины')),
                ('start_vaccine', models.DateField(null=True, verbose_name='Дата вакцинации')),
                ('validity_period_vaccine', models.IntegerField(default=0, verbose_name='Срок действия вакцины')),
                ('pet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_app.pet', verbose_name='Имя питомца')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(verbose_name='Тип обработки')),
                ('treatment_name', models.CharField(verbose_name='Название препарата')),
                ('start_treatment', models.DateField(verbose_name='Дата обработки')),
                ('validity_period_treatment', models.IntegerField(default=0, verbose_name='Срок действия обработки')),
                ('pet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddy_app.pet', verbose_name='Имя питомца')),
            ],
        ),
    ]
